---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность авторизоваться на сайте
  - Пользователя должен иметь возможность авторизоваться через GitHub
  - Пользователя должен иметь возможность авторизоваться через Discord
  - На странице авторизации должно быть доступно восстановление пароля
  - Пользователь должен иметь возможность создать игру и играть в неё с любым человеком, с ботом или другом
  - Пользователь должен иметь возможность отправить запрос на игру любому игроку или другу
  - Пользователь должен иметь возможность принять запрос на игру от любого игрока, друга или отклонить запрос
  - Пользователь должен иметь возможность выбирать уровень сложности задания в игре
  - Пользователь должен иметь возможность установить таймер продолжительности игры
  - Пользователь должен иметь возможность выбирать задание игры
  - Пользователь должен иметь возможность видеть код своего соперника в режиме онлайн
  - Пользователь должен иметь возможность сдаться и завершить игру
  - В игре должен быть чат, в котором могут общаться зарегистрированные пользователи
  - Пользователь должен иметь возможность просматривать статистику своего профиля и историю своих игр
  - Пользователь должен иметь возможность просматривать свой рейтинг и рейтинги других игроков
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1500 одновременных пользователей)
implicit:
  - Сайт должен быть доступен на разных языках (рус, eng) 
