---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность залогиниться на сайте
  - Пользователь должен иметь возможность создать игру и играть в неё с любым человеком, с ботом или другом
  - Пользователь должен иметь возможность отправить запрос на игру любому игроку или другу
  - Пользователь должен иметь возможность принять запрос на игру от любого игрока, друга или отклонить запрос
  - Пользователь должен иметь возможность выбирать уровень сложности задания в игре
  - Пользователь должен иметь возможность выбрать время таймера игры
  - Пользователь должен иметь возможность сдаться и завершить игру
  - Пользователь должен иметь возможность отправлять сообщения в чате
  - Пользователь должен иметь возможность просматривать свой рейтинг
  - Пользователь должен иметь возможность просматривать рейтинги других игроков
  - Пользователь должен иметь возможность просматривать историю своих игр
  - Пользователь должен иметь возможность видеть код своего соперника в режиме онлайн
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен быть доступен на разных языках (рус, eng) 
